// Copyright (c) Sean Lawlor
//
// This source code is licensed under both the MIT license found in the
// LICENSE-MIT file in the root directory of this source tree.

//! Schema introspection for shell integration.
//!
//! This module provides traits for message types that support runtime schema
//! introspection, enabling interactive shells to discover message formats and
//! send properly-typed messages.
//!
//! # Usage
//!
//! Actors opt-in to shell introspection by adding the `#[ractor_shell]` attribute
//! to their message type when deriving `RactorClusterMessage`:
//!
//! ```ignore
//! #[derive(RactorClusterMessage)]
//! #[ractor_shell]
//! pub enum MyMessage {
//!     Ping,
//!     #[rpc]
//!     GetValue(RpcReplyPort<i32>),
//! }
//! ```
//!
//! The derive macro will generate an implementation of [`SchemaProvider`] that:
//! - Returns a JSON schema describing the message variants
//! - Provides JSON-to-message deserialization
//! - Provides message-to-JSON serialization for responses

use serde_json::Value;

/// Error type for JSON deserialization failures.
#[derive(Debug, Clone)]
pub struct JsonDeserializeError {
    /// Description of what went wrong during deserialization.
    pub message: String,
}

impl JsonDeserializeError {
    /// Create a new deserialization error with the given message.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }

    /// Create an error for a missing required field.
    pub fn missing_field(field: &str) -> Self {
        Self::new(format!("missing required field '{}'", field))
    }

    /// Create an error for an invalid field type.
    pub fn invalid_type(field: &str, expected: &str) -> Self {
        Self::new(format!(
            "field '{}' has invalid type, expected {}",
            field, expected
        ))
    }

    /// Create an error for an unknown variant.
    pub fn unknown_variant(variant: &str) -> Self {
        Self::new(format!("unknown variant '{}'", variant))
    }
}

impl std::fmt::Display for JsonDeserializeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for JsonDeserializeError {}

/// Trait for message types that support shell introspection.
///
/// This trait is automatically implemented by the `#[ractor_shell]` derive attribute
/// when used with `RactorClusterMessage`. It enables interactive shells to:
///
/// 1. Discover the schema of an actor's message type
/// 2. Convert JSON input to properly-typed messages
/// 3. Convert message responses back to JSON
///
/// # Schema Format
///
/// The schema is returned as a JSON string with the following structure:
///
/// ```json
/// {
///   "variants": {
///     "VariantName": {
///       "fields": {"field1": "type1", "field2": "type2"},
///       "rpc": false
///     },
///     "RpcVariant": {
///       "fields": {"0": "type"},
///       "rpc": true,
///       "reply_type": "ReplyType"
///     }
///   }
/// }
/// ```
pub trait SchemaProvider: crate::Message + Sized {
    /// Returns a JSON schema describing this message type's variants and fields.
    ///
    /// The schema is a compile-time constant string generated by the derive macro.
    fn message_schema() -> &'static str;

    /// Deserialize a message from JSON given the variant name and arguments.
    ///
    /// # Arguments
    ///
    /// * `variant` - The name of the message variant (e.g., "Ping", "GetValue")
    /// * `args` - JSON object containing the variant's field values
    ///
    /// # Errors
    ///
    /// Returns [`JsonDeserializeError`] if:
    /// - The variant name is unknown
    /// - Required fields are missing
    /// - Field types don't match expected types
    fn from_json(variant: &str, args: Value) -> Result<Self, JsonDeserializeError>;

    /// Serialize this message to JSON.
    ///
    /// This is primarily used for serializing RPC responses back to the shell.
    fn to_json(&self) -> Value;
}
